[package]
name = "csc372_project"
version = "0.1.0"
authors = ["Kitty Elliott <kitty@glitchcat.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rotn"
path = "src/rot_n.rs"